### ISSUE TITLE
Saving to .npy 

### ISSUE THREAD

**Issue by plooney** [ndarray/Boost.NumPy#38]
I have tried to save an array to a .npy format to do further analysis. I have found an alternative to do this at 

https://github.com/rogersce/cnpy/blob/master/example1.cpp

**Comment by TallJimbo** [comment]
I think adding this to Boost.NumPy itself would be beyond the intended scope of the library, but thanks for the contribution; hopefully it can serve as a useful example for anyone else who wants to do this.
