### ISSUE TITLE
Segfault when calling `boost::numpy::get_builtin<T>`

### ISSUE THREAD

**Issue by alendit** [ndarray/Boost.NumPy#41]
Hi,

the problem occures when a shared library compiled with `Boost.NumPy` is linked to an executable.

To reprodue:

    git clone http://github.com/alendit/boost_numpy_segfault.git
    cd boost_numpy_segfault
    ./compile.sh  # will clone boost.numpy and compile it
    ./run.sh  # executes the binary and crash

See the `Makefile` for compile flags. The problem isn't limited to `double`, the same issue occurs when I use other types.

Tested with `clang-3.5` and `gcc-4.9` on `Ubuntu 14.10` with `libboost-1.55.0`.

**Comment by TallJimbo** [comment]
It's not clear to me how you're trying to use Python here - Boost.NumPy, Boost.Python, or any other way of calling the Python C API require you to do at least one of two things:
 - Build a compiled module as a shared library, and then import it in Python.
 - Embed the Python interpreter in your executable, which requires explicit initialization of the interpreter (see https://docs.python.org/2/extending/embedding.html).

In addition, with either of those approaches, when using Boost.NumPy, you'll also have to explicitly initialize that, by calling `boost::numpy::initialize()` (after initializing Python itself, but before doing anything else with Boost.NumPy).  Forgetting that is by far the most common reason people see segfaults when using the library.   I wish it wasn't necessary, by the way - but some sort of initialization call is essentially a requirement for anything that uses the NumPy C API, even if you use it indirectly through a library like Boost.NumPy.

**Comment by nbecker** [comment]
Could calling initialize be done via a global constructor?

**Comment by TallJimbo** [comment]
> Could calling initialize be done via a global constructor?

I don't think so, because it needs to happen after Python itself has been initialized, and regardless of whether you're extending or embedding, that happens after static initialization time.

**Comment by alendit** [comment]
Hi,

it may well be the `boost::numpy::initialize()` issue, in my real code I use the same file to create an embeded executable and a shared library. In case of the shared library, I don't think that I called `boost::numpy::initialize()`.

I'm closing the issue for now. I'll test it next week and re-open it, if it still persists.

**Comment by alendit** [comment]
Confirmed: placing `boost::numpy::initialize()` in the `BOOST_PYTHON_MODULE` solved the issue.
