### ISSUE TITLE
Warning with clang, icc

### ISSUE THREAD

**Issue by XWarin** [ndarray/Boost.NumPy#42]
Hi
Thank you for the library.
Here are some warnings by clang or icc
Best regards

CLANG :
/home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp:53:5: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
int const multi_iter::get_nd() const 
    ^~~~~~
/home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp:63:13: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
Py_intptr_t const multi_iter::shape(int n) const 

ICC :+1: 
In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(14),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ndarray.hpp(90): warning #858: type qualifier on return type is meaningless
    int const shape(int n) const { return get_shape()[n]; }
        ^

In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(14),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ndarray.hpp(93): warning #858: type qualifier on return type is meaningless
    int const strides(int n) const { return get_strides()[n]; }
        ^

In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(14),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ndarray.hpp(119): warning #858: type qualifier on return type is meaningless
    int const get_nd() const { return get_struct()->nd; }
        ^

In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(14),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ndarray.hpp(122): warning #858: type qualifier on return type is meaningless
    bitflag const get_flags() const;
            ^

In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(17),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ufunc.hpp(55): warning #858: type qualifier on return type is meaningless
    int const get_nd() const;
        ^

In file included from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy.hpp(17),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/internal.hpp(28),
                 from /home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(7):
/home/warin/GIT_REPOS/libstoc/boostpython/boost/numpy/ufunc.hpp(61): warning #858: type qualifier on return type is meaningless
    Py_intptr_t const shape(int n) const;
                ^

/home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(53): warning #858: type qualifier on return type is meaningless
  int const multi_iter::get_nd() const 
      ^

/home/warin/GIT_REPOS/libstoc/boostpython/libs/numpy/src/ufunc.cpp(63): warning #858: type qualifier on return type is meaningless
  Py_intptr_t const multi_iter::shape(int n) const 
              ^

**Comment by TallJimbo** [comment]
I actually disagree with the compilers on this; adding `const` to these returns has a small but useful effect: it prevents confusion with reference returns.  In other words, without `const`, a user might try
```
array.shape(1) = 3;
```
and think they've actually accomplished something, while all they've really done is modify a temporary.  Using `const` for the return value will make the above line fail to compile.

However, I don't like seeing compiler warnings either, so if you can provide me with the preprocessor pragma magic necessary to disable these warnings on just those files, I'd be happy to add it.

**Comment by XWarin** [comment]
Hi Jim

In ufunc.cpp and ndarray.cpp  add
#ifdef __clang__
#pragma clang diagnostic ignored "-Wignored-qualifiers"
#endif

For icc, it necessary to add in ufunc.hpp and ndarray.hpp (not sufficient
in cpp files)
#ifdef __INTEL_COMPILER
#pragma warning(disable:858)
#endif
Best regards

Xavier

**Comment by rubenvb** [comment]
I respectfully disagree that `const` return types (if not a reference or pointer) is meaningful.

Your example also fails to compile without `const`, see [Live demo](http://coliru.stacked-crooked.com/a/e753eae7efc6aee8):

    struct A
    {
      int f() { return 42; }
      const int g() const { return 43; }
    };

    int main()
    {
      A a;
      const A ca;
      a.f() = 1;
      ca.g() = 2;
    }

Which gives:

    main.cpp:5:19: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
         const int g() const { return 43; }
                       ^
    main.cpp: In function 'int main()':
    main.cpp:12:11: error: lvalue required as left operand of assignment
         a.f() = 1;
               ^
    main.cpp:13:12: error: lvalue required as left operand of assignment
         ca.g() = 2;
                ^
If this example is not what you meant, could you provide an example showing an unwanted modification of a temporary returned by a non-const member function?

**Comment by TallJimbo** [comment]
Sorry for the extreme delay on the response.  Anyhow, you've convinced me; I don't know what I was thinking of - I probably mistook the behavior of an old gcc ages ago as standard-mandated, and the incorrect thinking stuck with me.  I'll change all the const rvalue returns.

**Comment by TallJimbo** [comment]
Fixed and merged to master.
