### ISSUE TITLE
ImportError: libboost_numpy.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hiostreas** [ndarray/Boost.NumPy#43]
I installed Boost.NumPy as the instructions the library is installed, but python is not able to find it, my version is 2.7

**Comment by TallJimbo** [comment]
This sounds like a problem with your build system or environment; are you sure the installation library path is in whatever environment variables or other configuration systems you need to be able to link to it on your platform?

If so, some information on your platform, build tool, and link commands would be necessary to help debug the problem.

**Comment by hiostreas** [comment]
my SO is Ubuntu 12.04
inside of the directory Boost.NumPy-masters

I type:
$ mkdir build
$ cd build
$ cmake ..

RESULT 1:
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.3") 
-- Found PythonLibs: /usr/lib/libpython2.7.so
-- Found NumPy: version "1.6.1" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Using Python2
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   python
-- Boost Paths:
-- Include  : /usr/include
-- Libraries: /usr/lib/libboost_python.so
-- Configuring done
-- Generating done
-- Build files have been written to: /working/directory/Boost.Numpy-masters/build

$make (NO errors)

$sudo make install

RESULTS 2:
[ 46%] Built target boost_numpy
[ 53%] Built target dtype
[ 61%] Built target fromdata
[ 69%] Built target gaussian
[ 76%] Built target ndarray
[ 84%] Built target simple
[ 92%] Built target ufunc
[100%] Built target wrap
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/boost
-- Installing: /usr/local/include/boost/numpy
-- Up-to-date: /usr/local/include/boost/numpy/matrix.hpp
-- Up-to-date: /usr/local/include/boost/numpy/ufunc.hpp
-- Up-to-date: /usr/local/include/boost/numpy/numpy_object_mgr_traits.hpp
-- Up-to-date: /usr/local/include/boost/numpy/invoke_matching.hpp
-- Up-to-date: /usr/local/include/boost/numpy/internal.hpp
-- Up-to-date: /usr/local/include/boost/numpy/dtype.hpp
-- Up-to-date: /usr/local/include/boost/numpy/scalars.hpp
-- Up-to-date: /usr/local/include/boost/numpy/ndarray.hpp
-- Up-to-date: /usr/local/include/boost/numpy.hpp
-- Installing: /usr/local/lib/libboost_numpy.so

$cd ..
$python 
$make (I run my own makefile)
>>>import cv2
>>>import test


MY MAKEFILE FOR MY PROGRAM
PYTHON_VERSION = 2.7
PYTHON_INCLUDE = /usr/include/python$(PYTHON_VERSION)

# location of the Boost Python include files and library

BOOST_INC = /usr/include
BOOST_LIB = /usr/lib

# your filename here
TARGET = test

$(TARGET).so: $(TARGET).o
	g++ -shared -Wl,--export-dynamic $(TARGET).o -L$(BOOST_LIB) -lboost_python -L/usr/lib/python$(PYTHON_VERSION)/config -lpython$(PYTHON_VERSION) -o $(TARGET).so `pkg-config --libs opencv` `pkg-config --cflags opencv`

$(TARGET).o: $(TARGET).cpp
	g++ -I$(PYTHON_INCLUDE) -I$(BOOST_INC) -fPIC -c $(TARGET).cpp

test.cpp

// test.cpp
#include <boost/python.hpp>
#include <boost/numpy.hpp>
#include <boost/scoped_array.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>

namespace py = boost::python;
namespace np = boost::numpy;

void square(np::ndarray& array)
{
    if (array.get_dtype() != np::dtype::get_builtin<int>())
    {
        PyErr_SetString(PyExc_TypeError, "Incorrect array data type.");
        py::throw_error_already_set();
    }
    size_t rows = array.shape(0), cols = array.shape(1);
    size_t stride_row = array.strides(0) / sizeof(int), 
           stride_col = array.strides(1) / sizeof(int);
    cv::Mat mat(rows, cols, CV_32S);
    int *row_iter = reinterpret_cast<int*>(array.get_data());
    for (int i = 0; i < rows; i++, row_iter += stride_row)
    {
        int *col_iter = row_iter;
        int *mat_row = (int*)mat.ptr(i);
        for (int j = 0; j < cols; j++, col_iter += stride_col)
        {
            *(mat_row + j) = (*col_iter) * (*col_iter); 
        }
    }

    for (int i = 0; i < rows; i++, row_iter += stride_row)
    {
        int *col_iter = row_iter;
        int *mat_row = (int*)mat.ptr(i);
        for (int j = 0; j < cols; j++, col_iter += stride_col)
        {
            *col_iter = *(mat_row + j);
        }
    }
}


BOOST_PYTHON_MODULE(test)
{
   using namespace boost::python;
   def("square", square);
}

**Comment by hiostreas** [comment]
I included the following libraries it doesnt appear in test.cpp
#include <boost/python.hpp>
#include <boost/numpy.hpp>
#include <boost/scoped_array.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>

**Comment by TallJimbo** [comment]
I think your build command needs to at least have `-lboost_numpy`.  I think `-L/usr/local/lib` is probably implied and unnecessary, but it might be useful to add it and see if that helps just in case.

By the way, you'll also need to add a "boost:::numpy::initialize()" call to the beginning of your `BOOST_PYTHON_MODULE` block, but that's not what's causing problems here.

**Comment by TallJimbo** [comment]
Oh, also, it's a little strange in your traceback that it's finding gcc 4.8 for C but gcc 4.6 for C++; I don't expect that to cause problems, but you may want to make sure your CC and CXX variables are consistent.

**Comment by hiostreas** [comment]
How can I do that??

**Comment by TallJimbo** [comment]
Well, the simplest way would be to set:
```
export CC=/path/to/c-compiler
export CXX=/path/to/c++-compiler
```
(for the actual paths to the compilers you want to use, of course).

But it may be more useful to try to figure out why your system has a different default to begin with; did you install both of those with apt, or is one of them a custom install?

**Comment by hiostreas** [comment]
It didnt appear but in the make file I put -lboost_numpy

**Comment by TallJimbo** [comment]
Did that solve the problem for you, then?

**Comment by hiostreas** [comment]
nope, actually, its the same thing

**Comment by TallJimbo** [comment]
I'll try to reproduce when I have time, but I'm not optimistic (I'm on Ubuntu 14.04, which should be similar enough, but I suspect the problem is something specific to your configuration).  In the meantime: 
 - Could you verify that `/usr/local/lib/libboost_numpy.so` exists?
 - Does the "cannot open shared object file" error happen when you try to build your test module, or when you try to import it in Python?

**Comment by hiostreas** [comment]
yes I did, exists, I already did

**Comment by hiostreas** [comment]
I fix it now import perfect, 
I had the idea to change the permision of libboost_numpy.so
the command line that I used was(to be able to do that I had to go to the directory of libboost_numpy):
$sudo chmod 777 libboost_numpy.so

**Comment by hiostreas** [comment]
If you have more examples with openCV is perfect, thank you

**Comment by hiostreas** [comment]
Now I am trying to run some opencv codes
compiles perfect
imports perfect, but when I run the code happen the following erros:


python
import cv2
import camera_gray
Assertion failed (depth == CV_8U || depth == CV_16U || depth == CV_32F) in cvtColor, file /media/Data/OpenCV/opencv/modules/imgproc/src/color.cpp, line 7343
Traceback (most recent call last):
  File "try.py", line 5, in <module>
    camera_gray.gray_trans(img)
RuntimeError: /media/Data/OpenCV/opencv/modules/imgproc/src/color.cpp:7343: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cvtColor

I changed from CV_32S to CV_32F, CV_8U AND CV16U

and I get the following: Assertion failed (scn == 3 || scn == 4) in cvtColor


img = cv2.imread('image.jpg')
camera_gray.gray_trans(img)

c++ code

#include <boost/python.hpp>
#include <boost/numpy.hpp>
#include <boost/scoped_array.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>

using namespace std;
using namespace cv;
using namespace boost::python;
using namespace boost::numpy;


void gray_trans(ndarray& array) {


    // Check type
    
    cout << "Hello " <<  "image" << "!\n";
    size_t rows = array.shape(0), cols = array.shape(1);
    Mat greyMat;

    Mat colorMat(rows, cols, CV_32S);
    cout << "Hello " <<  "b_a_w" << "!\n";
    
    cvtColor(colorMat, greyMat, CV_BGR2GRAY);
    cout << "Show Image" << "!\n";
    imshow("b_a_w",greyMat);
   //return greyMat;
}

BOOST_PYTHON_MODULE(camera_gray)
{
    Py_Initialize();
    initialize();
    def("gray_trans",gray_trans);
}

makefile
PYTHON_VERSION = 2.7
PYTHON_INCLUDE = /usr/include/python$(PYTHON_VERSION)

BOOST_INC = /usr/local/include
BOOST_LIB = /usr/local/lib
OPENCV_LIB = $$(pkg-config --libs opencv)
OPENCV_INC = $$(pkg-config --cflags opencv)

TARGET = camera_gray

$(TARGET).so: $(TARGET).o
	g++ -shared -Wl,--export-dynamic $(TARGET).o -L$(BOOST_LIB) -lboost_python -lboost_numpy $(OPENCV_LIB) -L/usr/lib/python$(PYTHON_VERSION)/config -lpython$(PYTHON_VERSION) -o $(TARGET).so

$(TARGET).o: $(TARGET).cpp
	g++ -I$(PYTHON_INCLUDE) $(OPENCV_INC) -I$(BOOST_INC) -fPIC -c $(TARGET).cpp

**Comment by TallJimbo** [comment]
I'm afraid I don't know anything about OpenCV so I won't be much help on debugging this.  You may want to try their mailing list.

**Comment by hiostreas** [comment]
Can I have the maillist??

**Comment by TallJimbo** [comment]
Like I said, I'm not familiar with OpenCV, but google says this might be a good bet: http://answers.opencv.org/questions/

**Comment by p-zander** [comment]
I was also having the same issue. This is due to specific confiurations of the build system and is not an issue of this repo. When building with clang++-3.5 running the binary yielded the error in the title. Two solutions that both helped me:
1. Using g++ <b>or</b>
2. Adding to the libary path `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`
