### ISSUE TITLE
I solved the boost numpy for opencv

### ISSUE THREAD

**Issue by hiostreas** [ndarray/Boost.NumPy#44]
I just studied how is the numpy is made this is just a c++ function to write a file from a numpy image taken from opencv

          void gray_trans(np::ndarray& array) {
           if (array.get_dtype() != np::dtype::get_builtin<uchar>())
          {
               PyErr_SetString(PyExc_TypeError, "Incorrect array data type.");
               throw_error_already_set();
        
           }
  	    
  	    int rows = array.shape(0), cols = array.shape(1); 
  	    cout <<"row: "<< rows <<"\n";
  	    
  	    cout << "cols: "<< cols <<"\n"; 
  	    
        uchar *row_iter = reinterpret_cast<uchar*>(array.get_data());
       
        Mat mat(rows, cols, CV_8UC3);
        mat.data = (uchar *) row_iter;
	 
	    imwrite("result_Check.jpg",mat);
    
}

**Comment by ylqfp** [comment]
Good, need for that. Thanks!
