### ISSUE TITLE
Python  3.4.3 not compatible Boost Numpy

### ISSUE THREAD

**Issue by gxieaa** [ndarray/Boost.NumPy#47]
My Python version is 3.4.3, and I am trying to build Boost Numpy support for My Python Version

I revised the CMakeLists.txt as the second graph:
![python_requirement](https://cloud.githubusercontent.com/assets/6421620/9426604/dcf482ca-491a-11e5-8687-738cba68f595.png)

CmakeList result is passed and described as the third graph:
![my_cmakelist](https://cloud.githubusercontent.com/assets/6421620/9426606/e475b06e-491a-11e5-9496-e597159fb0a3.png)

However, when I try to make in Boost Numpy, there are the error for bad value, /usr/local/lib/libpython3.4m.a: error adding symbols
![boost_numpy_error](https://cloud.githubusercontent.com/assets/6421620/9428080/36fc1b0c-496b-11e5-8fd8-44ea6e272632.png)

Do Someone Know about how to solve this issue?

**Comment by TallJimbo** [comment]
This looks like a static vs. shared libraries problem: you're trying to use a boost shared library (.so) with a Python static library (.a).  At least on Linux, it's much more common to build shared libraries when building against Python, and I'm not sure this library will work at all with static linking.  Does `/usr/local/lib/libpython3.4m.so` exist?  If not, you probably need to rebuild Python to include shared libraries (`--enable-shared` to configure, I think).

**Comment by TallJimbo** [comment]
I'm hoping the last post fixed this issue (if not, some recent changes may have). Please reopen if this is still a problem.
