### ISSUE TITLE
cannot find boost_python

### ISSUE THREAD

**Issue by hycis** [ndarray/Boost.NumPy#49]
when i try to do a cmake i get the cannot find boost_python error, anyone knows how to fix this? Thanks.

```bash
Hyciss-MacBook-Pro:build Hycis$ cmake ..
-- Using Python2
CMake Error at /usr/local/Cellar/cmake/3.3.1/share/cmake/Modules/FindBoost.cmake:1245 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:41 (find_package)


-- Boost Paths:
-- Include  : /usr/local/include
-- Libraries: 
-- Configuring incomplete, errors occurred!
See also "/Volumes/Storage/Packages/Boost.NumPy/build/CMakeFiles/CMakeOutput.log".
```

**Comment by kevinmartinmauro** [comment]
Were you able to find a solution? Hitting a similar problem

**Comment by TallJimbo** [comment]
Where is your `boost_python` library actually located, what is its full name, and what version of Python are you using?

**Comment by kevinmartinmauro** [comment]
I think my version of Python might be incompatible --- I'm running 3.3.5. What are you running, or what should I run?

**Comment by TallJimbo** [comment]
I'm currently still doing all of my work on Python 2.7.  But I have at least gotten the library to build and link with Python 3 (though I just tried it for the first time tonight).  That doesn't mean it will work, and the indication from @nbecker is that it won't until I include his fixed patch from #25.  But I was able to get it to find and link against `boost_python` with both Python 2 and Python 3 using cmake, at least with everything installed in `/usr`.  I'm sure I've gotten it working with Boost installed in a less standard location in the past, but I'm not currently in a position to try that right now, as I don't have Boost installed anywhere else.

**Comment by marcel-goldschen-ohm** [comment]
Here's a step-by-step of how I installed with cmake on MacOSX Yosemite for Boost and Python3 and Boost.Python that were installed via Homebrew. You may have to edit the paths for your system. Hopefully it helps.

```
brew install python3
brew install boost
brew install boost-python --with-python3
brew install boost-build
brew install cmake

git clone https://github.com/ndarray/Boost.NumPy.git
cd Boost.Numpy
mkdir build
cd build
cmake -v -DPYTHON_LIBRARY=/usr/local/Frameworks/Python.framework/Versions/3.4/lib/libpython3.4m.dylib -DPYTHON_EXECUTABLE=/usr/local/Frameworks/Python.framework/Versions/3.4/bin/python3.4m -DBoost_INCLUDE_DIR=/usr/local/include -D Boost_NO_BOOST_CMAKE=ON ..
make
```

After running make, headers are in Boost.Numpy/boost/ and library is in Boost.Numpy/build/lib/.

**Comment by TallJimbo** [comment]
I'm assuming the last post here cleared up the issues everyone was having here; please reopen or create a new issue if that's not the case.
