### ISSUE TITLE
Ambiguous argument in from_data (in example + documentation)

### ISSUE THREAD

**Issue by gnthibault** [ndarray/Boost.NumPy#50]
Hi all,

First of all, thank you very much for your work, I really appreciate it to be able to use ndArrays as output/input in my code, as I use both C++ and python for my project.

I just wanted to point out that something may be a bit ambiguous in your example, and in the documentation, regarding the manipulations of ndArrays in C++ : the stride attribute.

The stride is expressed in terms of bytes, of course, that seems clear in the file "wrap.cpp"

But, when reading the files fromdata.cpp and ndarray.cpp; I see this:

// Create an array in C++
int arr[] = {1,2,3,4} ; 
// Create the ndarray in Python
np::ndarray py_array = np::from_data(arr, np::dtype::get_builtin<int>() , p::make_tuple(4), p::make_tuple(4), p::object());

As there are 4 elements in your buffer, and each element is assumed to be 4 bytes in size, it may be a bit less ambiguous to use p::make_tuple(sizeof(int)) instead of p::make_tuple(4) in the stride argument.

Of course, this is nothing important, but it would be easy to modify it, or to modify the documentation of the from_data method in order to understand easily that strides is expressed in byte.

Because here is what say the documentation : 
* the ``shape`` of the ndarray as Python object
* the ``strides`` of each dimension of the array as a Python object

Again, this is is only an advice not a real issue at all, because I find myself having some trouble exporting data because of my misunderstanding of the stride argument in the first place.

Thank you again for your work.

**Comment by TallJimbo** [comment]
Thanks; very good point.  I've fixed a couple of examples where this was especially bad (including the one you brought up in fromdata.rst), but a quick glance shows the documentation to be in worse shape than I had realized, and it'll probably be a while before I can get around to really cleaning it up.
