### ISSUE TITLE
access violation in dtype::get_builtin<>() with python 3.4.3

### ISSUE THREAD

**Issue by wlter** [ndarray/Boost.NumPy#52]
Hello,

first of all, thank you very much for building this great library. Unfortuately I have trouble making it work.

When creating new ndarrays, it seems dtype::get_builtin<>() is quite essential, and this is exactly the function which seems to cause problems. When code such as this is called from python, it causes an access violation in python.exe

void array_test::sum(boost::python::numeric::array arr)
{
  boost::numpy::dtype::get_builtin< double >();
  return(5);
}

The debugger takes me down into dtype.cpp to these lines (57 onwards):

BUILTIN_FLOAT_DTYPE(64);

This happens with Python 3.4.3 (Anaconda), Boost::Python 1.59, Boost::Numpy from two days ago, on two independent Windows 7 Machines. And with various template arguments, too.

Could this be due to the python version? Is it actually okay, to use 3.x?

**Comment by TallJimbo** [comment]
First off, please double check that you're calling `boost::numpy::initialize()` in your module's init function.  Failing to do that is by far the most common reason for segfaults.  I wish that weren't necessary, but the NumPy C API seems to require it.

If that's not the problem, there is a possibility it's a problem with using Python 3.x; while there have been some reports of the library being used successfully with Python 3, it's had much less testing than with Python 2.

**Comment by wlter** [comment]
D'oh! The init-part is exactly what was missing. Sorry to bother with that question. And thank you very much for your quick response.
