### ISSUE TITLE
create two array in one python function

### ISSUE THREAD

**Issue by jingpengwu** [ndarray/Boost.NumPy#54]
Hi,

I really like this library. It is convenient to use and have good examples.

I created two numpy arrays in one python function using `from_data`. The owner is bp::object().

Although the two arrays were stored separately in memory, the first array was always over written by the second array! I think that this may be due to the same owner, but have no idea to fix it!

**Comment by TallJimbo** [comment]
Can you please post a code sample?

**Comment by jingpengwu** [comment]
Sorry for the delayed reply.

I have solved this problem by simply using one array...

the problematic code is here:

I transform two boost multiarray to numpy arrays:
https://github.com/seung-lab/znn-release/blob/0fd9d44ed5a686407326286fda51f28e7f46c0e4/python/malis/pymalis.cpp#L37

the transformation function is here:
https://github.com/seung-lab/znn-release/blob/0fd9d44ed5a686407326286fda51f28e7f46c0e4/python/malis/pymalis.cpp#L37

Thanks a lot.
Jingpeng

**Comment by TallJimbo** [comment]
How is the memory pointed at by a `qube_p` object managed?  If it is deallocated by `qube_p`'s constructor, as it appears from the definition of `cubelist2array`, I think you have bigger problems than just overwriting data: when `cubelist2array` returns, the `qube_p` managing its pointer goes out scope, deleting the memory in the `boost::numpy::ndarray`.  That can lead to segfaults and other undefined behavior, since you'll be dereferencing an invalid pointer.

The easiest way to make that safe would be to call `copy()` on the result of `from_data`, which would make a deep copy of the original array owned by the new array.  If you want to return a view, you need to find some way to keep your `qube_p` alive after `cubelist2array` returns.  The easiest way to do that would be to allocate it inside a shared pointer, and use that shared pointer as the "owner" argument to `from_data`.

**Comment by jingpengwu** [comment]
Thanks for the explanation!  The `qube_p` is a `shared pointer` of a boost `multi_array`. It have the problem of memory release.

The `copy()` works with a overhead of copying data.

Making the shared pointer to be the `owner` sounds a perfect solution. But the `owner` should be a python object rather than the `shared pointer`, which is the `qube_p` in my case. I tried bp::object( tqp ), but get an error:
```
TypeError: No to_python (by-value) converter found for C++ type: std::shared_ptr<znn::v4::qube<float> >
```

**Comment by nbecker** [comment]
can you try boost::shared_ptr?

On Mon, Nov 30, 2015 at 11:34 AM, Jingpeng Wu <notifications@github.com>
wrote:

> Thanks for the explanation! The qube_p is a shared pointer of a boost
> multi_array. It have the problem of memory release.
>
> The copy() works with a overhead of copying data.
>
> Making the shared pointer to be the owner sounds a perfect solution. But
> the owner should be a python object rather than the shared pointer, which
> is the qube_p in my case. I tried bp::object( tqp ), but get an error:
>
> TypeError: No to_python (by-value) converter found for C++ type: std::shared_ptr<znn::v4::qube<float> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndarray/Boost.NumPy/issues/54#issuecomment-160681160>.
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by jingpengwu** [comment]
I still get an error:
`TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<float>`

Here is the code:
```
template <typename T>                                                           |
inline np::ndarray                                                              |
cubelist2array( bp::object const & self, std::vector<cube_p< T >> clist )       |
{                                                                               |
    // number of output cubes                                                   |                                                                                                                            
    std::size_t sc = clist.size();                                              |
    std::size_t sz = clist[0]->shape()[0];                                      |
    std::size_t sy = clist[0]->shape()[1];                                      |
    std::size_t sx = clist[0]->shape()[2];                                      |
                                                                                |
    // temporal 4D qube pointer                                                 |                                                                                                                            
//    qube_p<T> tqp = get_qube<T>( vec4i(sc,sz,sy,sx) );                        |                                                                                                                            
    T* tqp = new T[sc*sz*sy*sx];                                                |
                                                                                |
    for (std::size_t c=0; c<sc; c++)                                            |
    {                                                                           |
        for (std::size_t k=0; k<sz*sy*sx; k++)                                  |
            tqp[c*sz*sy*sx+k] = clist[c]->data()[k];                            |
    }                                                                           |
                                                                                |
    // return ndarray                                                           |                                                                                                                            
    np::ndarray arr = np::from_data(                                            |
        tqp,                                                                    |
        np::dtype::get_builtin<T>(),                                            |
        bp::make_tuple(sc,sz,sy,sx),                                            |
        bp::make_tuple(sx*sy*sz*sizeof(T), sx*sy*sizeof(T),                     |
                       sx*sizeof(T), sizeof(T)),                                |
        bp::object( boost::shared_ptr<T>(tqp) ));                               |
    return arr;                                                                 |
}                             
```

**Comment by TallJimbo** [comment]
Ah, my mistake.  I was confusing a feature in the higher-level ndarray/ndarray library with a feature here; there's no direct support for using a shared_ptr as an owner in Boost.NumPy.

That is something you can add on your own, though.   You just need to create a `PyObject *` that holds your `shared_ptr` and deallocates it at the right time, then make a `boost::python::object` that refers to it.  You can use the Python C API's [capsule](https://docs.python.org/2.7/c-api/capsule.html) to do the first part, and the Boost.Python documentation can tell you how to do the rest; create a [handle](http://www.boost.org/doc/libs/1_59_0/libs/python/doc/v2/handle.html#handle-spec) and use that to create an [object](http://www.boost.org/doc/libs/1_59_0/libs/python/doc/v2/object.html#object-spec).

**Comment by jingpengwu** [comment]
It seems that `from_data` is the only way to assign value to a numpy array. The following code do not work.

```
template <typename T>                                                           |
inline np::ndarray                                                              |
cubelist2array( bp::object const & self, std::vector<cube_p< T >> clist )       |
{                                                                               |
    // number of output cubes                                                   |                                                                                                                            
    std::size_t sc = clist.size();                                              |
    std::size_t sz = clist[0]->shape()[0];                                      |
    std::size_t sy = clist[0]->shape()[1];                                      |
    std::size_t sx = clist[0]->shape()[2];                                      |
                                                                                |
    // create an empty ndarray                                                  |                                                                                                                            
    np::ndarray arr = np::empty(                                                |
        bp::make_tuple(sc,sz,sy,sx),                                            |
        np::dtype::get_builtin<T>());                                           |
                                                                                |
    // copy the data                                                            |                                                                                                                            
    int k = 0;                                                                  |
    for (std::size_t c=0; c<sc; c++)                                            |
        for (std::size_t z=0; z<sz; z++)                                        |
            for (std::size_t y=0; y<sy; y++)                                    |
                for (std::size_t x=0; x<sx; x++)                                |
                {                                                               |
                    arr(c,sz,sy,sx,k) = clist[c]->data()[k];                    |
                    k++;                                                        |
                }                                                               |
    return arr;                                                                 |
}
```

**Comment by TallJimbo** [comment]
(sorry for the slow reply)

That's partially correct.  `boost::numpy::ndarray` does not define a method for direct access to array values, but you can use `get_data` and some stride arithmetic to do that (though that's not really the purpose of this library, as suggested by how difficult that is).
