### ISSUE TITLE
compiling error 'error: ‘NPY_FLOAT16’ was not declared in this scope'

### ISSUE THREAD

**Issue by assassin5615** [ndarray/Boost.NumPy#58]
the error is caused by BUILTIN_FLOAT_DTYPE(16) at dtype.cpp:60. had to comment out this line to compile. anything I missed here?

Thanks

**Comment by TallJimbo** [comment]
Could you tell me your what OS, architecture, and NumPy version are?  I'm guessing this is just an environment that I didn't anticipate that I'll need to add some preprocessor checks for, but it's possible NumPy has been changing things and I haven't kept up.

**Comment by assassin5615** [comment]
I was compiling with python 2.6.6.  numpy 1.4.1 on linux (SL 6.0).

**Comment by TallJimbo** [comment]
Fix merged to master at 191c9ddfff7e8245ac4e9945d673a1237631bd3c.
