### ISSUE TITLE
Error in Linux installation - file not found

### ISSUE THREAD

**Issue by priyankakancharla** [ndarray/Boost.NumPy#67]
Hi,

I am trying to install this in a Ubuntu system. The build files get generated but when I execute make the following error occurs ( in attached picture). Any help will be much appreciated. Thank you.

Regards,
Priyanka
![screenshot from 2016-07-28 16-26-39](https://cloud.githubusercontent.com/assets/16767029/17230400/a75c66fe-54e1-11e6-8016-f721a0cd1522.png)

**Comment by TallJimbo** [comment]
I'm afraid I've never seen this before, and I don't really have any idea what's going wrong.  Could you try building with `make VERBOSE=1` to see the full command, and in particular, the `-I` options that gcc is getting?

**Comment by priyankakancharla** [comment]
Thank you for replying! I didn't change anything and tried again after a few days and I attached the image of what happened this time. Does this mean it worked? Thanks in advance.
![screenshot from 2016-08-03 12-35-33](https://cloud.githubusercontent.com/assets/16767029/17375580/2fcf3b12-5977-11e6-9d45-6a76d2e85fdd.png)

**Comment by TallJimbo** [comment]
Looks like it; you could also try `make test` to make sure.

**Comment by priyankakancharla** [comment]
The folder hierarchy is confusing me a little. From which folder should I execute "make test" from? Sorry if this is a very basic question. Thanks a lot for your help.

**Comment by TallJimbo** [comment]
Ah, sorry, I didn't look closely enough at your outputs to diagnose the problem.  There are indeed a lot of build systems here.  If you want to build the library using cmake, you'll want to cd to the root directory, create a *new* build directory there, and run all make commands within that (this is the usual pattern for using cmake with any project):
```
$ cd Boost.Numpy      # or whatever - you should have README.md in your current directory after this
$ mkdir build
$ cd build
$ cmake ..
$ make
$ make test
$ make install
```
If you want to build the documentation, that's an entirely separate makefile that isn't generated by cmake:
```
$ cd libs/numpy.doc/
$ make
```

**Comment by priyankakancharla** [comment]
I tried to execute as you suggested but "make" doesn't work. Please see image.
![screenshot from 2016-08-03 13-38-09](https://cloud.githubusercontent.com/assets/16767029/17377558/d84ed470-597f-11e6-9207-f7a23b5939ba.png)

**Comment by TallJimbo** [comment]
It looks like it can't find where you've installed Boost.  Are you using the version provided by `apt`?  If so, make sure you've installed the `-dev` packages for Boost as well.  If not, you'll need to run e.g.
```
BOOST_DIR=/path/to/boost cmake ..
```
from the build directory to tell it where you've installed boost.

**Comment by priyankakancharla** [comment]
I installed boost using apt. And followed what you said and it worked! Thanks a lot for the detailed and prompt replies
![screenshot from 2016-08-03 14-02-58](https://cloud.githubusercontent.com/assets/16767029/17378407/6c322ff4-5983-11e6-878b-fe5bac5142dd.png)
![screenshot from 2016-08-03 14-03-21](https://cloud.githubusercontent.com/assets/16767029/17378412/6f337014-5983-11e6-8c81-4c584fe244ad.png)

. Really appreciate your help.

**Comment by TallJimbo** [comment]
Glad we got it working!

**Comment by priyankakancharla** [comment]
How can I check what python version is being used while installing boost and boost.python? I need it to work on python 3 so that I can install selective_search but I think it is defaulting to python 2? 
Thanks in advance.

**Comment by TallJimbo** [comment]
When you run `cmake`, it will say "Using Python 3" if it is doing so.  If you use
```
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3 ..
```
(or whatever is appropriate for your Python 3 executable instead of just `cmake ..`, I think that should be all you need.

**Comment by priyankakancharla** [comment]
Do I need to install "boost" for python3 with apt as well? It is throwing an error that it can't find the boost_python3.
![screenshot from 2016-08-03 14-31-25](https://cloud.githubusercontent.com/assets/16767029/17379297/5c15906c-5987-11e6-9e32-90012613b69f.png)

**Comment by TallJimbo** [comment]
Perhaps; it may also be that `apt` installed it with a non-standard name.  You should check both whether there's an `apt` package you've missed, and look at the results of `ls /usr/lib/libboost_python*` to see if anything looks like a Boost.Python library for Python 3.

**Comment by priyankakancharla** [comment]
Unfortunately I do not see any such file. I am not sure how to get boost for python3 using apt. There seems to be way by downloading the tar file and running the bash script to install it but I tried that earlier and it didn't work. Do you have any ideas?
Thanks again!

**Comment by TallJimbo** [comment]
The tar file is the standard approach, but @stefanseefeld has recently provided another way to build Boost.Python that might work for you; here are his instructions (just copied from an email he sent to a list I'm on).
>
> Building Boost.Python is now very simple:
> 
> * clone the repo via `git clone https://github.com/boostorg/python.git` and switch to the 'develop' branch
> 
> * configure a build via `scons config --python=... --boost-prefix=...`
> 
> * build and test via `scons test`
>

I also suspect there are many others in the same situation as you; googling "Ubuntu Boost.Python Python 3" or similar may lead you to some hints.

**Comment by priyankakancharla** [comment]
Hey,
I made it work using this solution in another issue thread - just copy pasting it here :

we already have this installed:

/usr/lib/x86_64-linux-gnu/libboost_python-py34.so

so, I did...

cd /usr/lib/x86_64-linux-gnu/
sudo ln -s libboost_python-py34.so libboost_python3.so

and selective_search_py compiled.


Thanks a lot for taking so much time and helping me out :).
