### ISSUE TITLE
Need release tags

### ISSUE THREAD

**Issue by bhill-slac** [ndarray/Boost.NumPy#69]
Could you create a release tag or tags?
It's helpful for collaboration to be able to easily communicate which version of boost.numpy is being used.
Thanks!

**Comment by TallJimbo** [comment]
I agree that would have been a good thing to do a while ago, but I'm actually just about to announce this package's deprecation: all of this functionality has been recently added to Boost.Python itself, and I'm not anticipating making further changes to this version if I can avoid it.  That will be especially true when the next Boost release (1.63) goes out.
