### ISSUE TITLE
boost::python v1.63 mangles py2 for py3 build with numpy

### ISSUE THREAD

**Issue by abemammen** [ndarray/Boost.NumPy#72]
with the integration of numpy into v1.63, it appears there is mangling of python2 libs for python3 environments.
Run time error:
Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python.dylib

built on mac with brew:
brew install boost
brew install boost-python --with-python3

**Comment by TallJimbo** [comment]
@stefanseefeld may have something useful to say about this, but in general bugs in the Numpy support now bundled with Boost.Python should be reported (I think) at https://github.com/boostorg/python.

**Comment by stefanseefeld** [comment]
yes, please submit any issues with Boost.Python to https://github.com/boostorg/python/issues.
Thanks !
