### ISSUE TITLE
Does not build in boost 1.63?

### ISSUE THREAD

**Issue by macdew** [ndarray/Boost.NumPy#76]
I have built boost 1.63 with python (v3.5.3), but I get linker errors trying to use the new numpy classes.  Other boost::python classes work fine, like boost::python::object, boost::python::throw_error_already_set etc.

What special magic compile flag is required to include numpy support in boost 1.63?  It doesn't appear to be documented on the boost python build pages.

**Comment by TallJimbo** [comment]
It sounds like you're trying to use the version of this library that's now bundled with Boost itself (which is what I'd recommend).  If that's the case, please report bugs at https://github.com/boostorg/python.

**Comment by macdew** [comment]
Ah ok, shall do...  And indeed, I'm trying to port from using this library directly to the one bundled in boost 1.63.

Note - I have spotted that the boost build process creates a .dll but no corresponding .lib file.  That suggests that nothing is being exported.

**Comment by macdew** [comment]
Ok, as suspected, the library as per boost 1.63 does not export any symbols.  Therefore no lib is created, meaning both a boost build failure and of course no usable boost numpy library.  I will revert my upgrade and wait for boost 1.64 as the issues have already been reported and fixed.

**Comment by macdew** [comment]
Update - boost 1.64 beta 2 does not work correctly either.  Have created a corresponding issue on their issues page.
