### ISSUE TITLE
64bit python call c and got OSError: exception: access violation writing 0xFFFFFFFF99222A60

### ISSUE THREAD

**Issue by Jasonqian1** [ndarray/Boost.NumPy#78]
We have an app(c++) called from python and it works great on Linux and windows 32-bit python.
When using 64-bit python, we got error "exception: access violation writing 0xFFFFFFFF99222A60".
Checking our server, it seems work without any problem. but the python gives an error and stop the application.

-- c --
class myPythonAPI
{
public:
	myPythonAPI();
	int  createService(const char* serviceName){ /* run our application*/};
}
extern "C" { 
   __declspec(dllexport) myPythonAPI* loadInstance(){ return new myPythonAPI(); }
   __declspec(dllexport) int createService(myPythonAPI* obj, const char* serviceName) { eturn obj->createService(serviceName);
};

-- python --
from ctypes import *
lib = cdll.LoadLibrary('xxxxxxx.dll')

lib.createService.argtypes=[c_int,ctypes.c_char_p]
lib.createService.restype=ctypes.c_int

class myDriver(object):
         def __init__(self):
        self.obj = lib.loadInstance()

    def create_services(self,servicename):
        result=lib.createService(self.obj,servicename)
        return result

driver=myDriver()
driver.create_services(b"myExample")

Thanks for the help
Jason

**Comment by TallJimbo** [comment]
I think you may be posting to the wrong project - it looks like you're using ctypes, not Boost.Python, and I don't see any sign of the NumPy bindings associating with this GitHub repo.

**Comment by Jasonqian1** [comment]
Sorry about this. Which project should I post to?  
Thanks
Jason

Sent from my iPhone

On Jan 22, 2018, at 2:58 PM, Jim Bosch <notifications@github.com> wrote:

I think you may be posting to the wrong project - it looks like you're using ctypes, not Boost.Python, and I don't see any sign of the NumPy bindings associating with this GitHub repo.

**Comment by TallJimbo** [comment]
I'm afraid I really don't know; you could try one of the main Python mailing lists, but I'm also quite certain there isn't enough information here about what you're doing for them to be able to help much.
