### ISSUE TITLE
runtime error with python3 :RuntimeError: _ARRAY_API is not PyCObject object

### ISSUE THREAD

**Issue by hwl311** [ndarray/Boost.NumPy#80]
Python 3.5.2 + ubuntu 16.04 amd64 + boost1.58 , np::initialize() report runtime error.
python2.7 is ok
my code:
#include <boost/python.hpp>
#include <boost/numpy.hpp>
#include <numpy/arrayobject.h>
#include <Python.h>
#include <iostream>
#include <string>

using namespace std;
using namespace boost::python;
namespace p = boost::python;
namespace np = boost::numpy;

p::object greet(p::object const & c)
{
    p::tuple shape = p::make_tuple(3, 5);
    np::dtype dtype = np::dtype::get_builtin<double>();
    np::ndarray a = np::zeros(shape, dtype);
    return p::make_tuple('a','b',c,a);
}

int initnp()
{
    import_array();
}

BOOST_PYTHON_MODULE(nf)
{
    initnp();
    np::initialize();
    def("greet", greet);
}

**Comment by TallJimbo** [comment]
If you're using `boost::numpy`, you shouldn't need to include `numpy/arrayobject.h` directly, and you shouldn't need to call `import_array()` (that's what `np::initialize()` does, actually).

I should add that this library is now deprecated: if you're able to move up to boost 1.63 or newer, you can use the Numpy support directly included in Boost.Python (essentially the same API as this library, but under namespace `boost::python::numpy`).

**Comment by hwl311** [comment]
think you!
