### ISSUE TITLE
ZN5boost6python5numpy10initializeEb: symbol not found

### ISSUE THREAD

**Issue by tonny2v** [ndarray/Boost.NumPy#83]
I installed boost numpy in a docker instance (alpine-3.8) and built a python extension but I cannot import the python module I built.

using ldd, I have

    ldd /usr/local/lib/python3.7/site-packages/pydhs-1.6.6-py3.7-linux-x86_64.egg/dhs.cpython-37m-x86_64-linux-gnu.so
	ldd (0x7f5a0cbb9000)
	libboost_python3.so.1.66.0 => /usr/lib/libboost_python3.so.1.66.0 (0x7f5a0c726000)
	libpython3.7m.so.1.0 => /usr/local/lib/libpython3.7m.so.1.0 (0x7f5a0c1ca000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f5a0be77000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f5a0bc65000)
	libc.musl-x86_64.so.1 => ldd (0x7f5a0cbb9000)
	libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x7f5a0b7df000)
    Error relocating /usr/local/lib/python3.7/site-packages/pydhs-1.6.6-py3.7-linux- 
    x86_64.egg/dhs.cpython-37m-x86_64-linux-gnu.so: _ZN5boost6python5numpy10initializeEb: symbol not found
    /work # cd /usr/local/lib64/

**Comment by TallJimbo** [comment]
It looks like you're trying to use the version of this library that's now included in Boost itself (I can tell from the `boost::python::numpy` namespace for the missing symbol, as opposed to the `boost::numpy` namespace used here).  And that's certainly what I'd recommend doing; the code hosted here is deprecated and no longer maintained.  But in that case you'll be better off reporting problems at https://github.com/boostorg/python, where the integrated version lives.
